### PR TITLE
Coverage Eligibility, Benefit Packages, Claims request, and PreAuthorization Monitor Processes

### PR DESCRIPTION
**Pull request by its-kios09**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Screenshots
claims managment
PreAuth

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by its-kios09** [comment]
@donaldkibet  I need your suggestion on this PR we merged our work with omosh for testing  and test are failing I have gone through the files I can't see any issues

**Comment by donaldkibet** [comment]
@its-kios09, please resolve the merge conflicts so we can address the build error. Let's prioritize submitting small PRs for easier review and tracking. For example, start with the initial layout without functionality and add features incrementally. For large features, it's best to split them into multiple PRs.

**Comment by its-kios09** [comment]
> @its-kios09, please resolve the merge conflicts so we can address the build error. Let's prioritize submitting small PRs for easier review and tracking. For example, start with the initial layout without functionality and add features incrementally. For large features, it's best to split them into multiple PRs.

@donaldkibet Apologies, but yesterday we combined our work with Omosh on the team's recommendation to combine the HIE work into a single branch. Thanks for the heads up

**Comment by Omoshlawi** [comment]
@donaldkibet , please dont merge this PR, I will be issueing a new one with everything in this and cleaned up too.
@its-kios09 , you can close it.

**Comment by its-kios09** [comment]
> @donaldkibet , please dont merge this PR, I will be issueing a new one with everything in this and cleaned up too. @its-kios09 , you can close it.

@Omoshlawi before I close please confirm for the PR will contain all the work we did with you and jacinta on HIE even claims form?

**Pull request closed without merging**
