### PR TITLE
(feat) : KHP3-6584 add encounters to medical history tab in morgue module

### PR DESCRIPTION
**Pull request by its-kios09**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
see:- https://thepalladiumgroup.atlassian.net/browse/KHP3-6584

## Screenshots
medicalHistory

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by donaldkibet** [comment]
Thanks @its-kios09, this is difficult to review given the amount of files changed.

**Comment by donaldkibet** [comment]
Please resolve the conflicts

**Review by donaldkibet — APPROVED** [review]

**Comment by donaldkibet** [comment]
@its-kios09 seems we have conflicts as we merge some additional work in

**Comment by ojwanganto** [comment]
This PR is not clear. Kindly update it to reflect the morgue module. Thanks, @its-kios09

**Pull request merged**
