### PR TITLE
feat: payment points & timesheets

### PR DESCRIPTION
**Pull request by amosmachora**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
This is initial work on the timesheets and payment points feature. Currently I have managed to complete the payment points feature (IMO). You can now be able to see the bills per payment point correctly _(watch video)_ and also create a payment point. I am actively working on the timesheets feature.

## Screenshots
https://github.com/user-attachments/assets/03900c64-2bea-40c7-a713-18b653b77a6a

### Current Timesheets Progress
image
Note that the clock in /out functionality will be one button. A functionality to check whether the logged in cashier has an active timesheet and render the appropriate button will be provided.

#### Clock In Modal
image

#### Clock Out Modal
image

## Related Issue

*None.*

## Other
cc @donaldkibet .

### CODE REVIEW

**Comment by amosmachora** [comment]
@ojwanganto whenever I try to create or get a timesheet I get a **500** internal server error. I need a backend guy to help.

**Comment by ojwanganto** [comment]
Share the payload that you are using

**Comment by amosmachora** [comment]
> Share the payload that you are using

I am hitting this endpoint `/ws/rest/v2/cashier/timesheet` with a payload that looks something like this.

```
{
cashier: string; 
cashPoint: string;
clockIn: string 
}
```
on fetching timesheets I hit the same URL but with a GET method.

**Comment by donaldkibet** [comment]
Ping @amosmachora lefts have this merged in

**Comment by amosmachora** [comment]
@donaldkibet I still have that issue with dev so I can`t record a video.

**Comment by donaldkibet** [comment]
Give it another try, i have updated the database

**Review by donaldkibet — APPROVED** [review]

**Pull request merged**
