### PR TITLE
Khp3 6465 add claim coverage eligibility benefits package preauthorization and claim requests

### PR DESCRIPTION
**Pull request by Omoshlawi**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Screenshots

https://github.com/user-attachments/assets/3eddf65a-1cf9-4be4-8d19-f00ece4e2bf1

****claims Management****
cla

## Related Issue

https://thepalladiumgroup.atlassian.net/browse/KHP3-6465

## Other

*None.*

### CODE REVIEW

**Comment by donaldkibet** [comment]
@Omoshlawi check why build is failing

**Comment by Omoshlawi** [comment]
@donaldkibet , seems like its an issue with patient flag esm

`@kenyaemr/esm-patient-flags-app:test: ERROR: command finished with error: command (/home/runner/work/kenyaemr-esm-3.x/kenyaemr-esm-3.x/packages/esm-patient-flags-app) yarn run test exited (1)
@kenyaemr/esm-pharmacy-app:test: cache miss, executing 861c724ca1e91cac
command (/home/runner/work/kenyaemr-esm-3.x/kenyaemr-esm-3.x/packages/esm-patient-flags-app) yarn run test exited (1)

 Tasks:    4 successful, 5 total
Cached:    0 cached, 5 total
  Time:    23.164s 

 ERROR  run failed: command  exited (1)
Error: Process completed with exit code 1.`

**Comment by donaldkibet** [comment]
cc @Omoshlawi kindly resolve conflicts

**Comment by Omoshlawi** [comment]
> cc @Omoshlawi kindly resolve conflicts

Done @donaldkibet

**Comment by Omoshlawi** [comment]
> cc @Omoshlawi kindly resolve conflicts

@donaldkibet Done

**Comment by ojwanganto** [comment]
This is still not a priority.

**Pull request merged**
