### PR TITLE
(feat) KHP3-6563: add deceased details page in morgue module

### PR DESCRIPTION
**Pull request by its-kios09**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
see:- https://thepalladiumgroup.atlassian.net/browse/KHP3-6563

## Screenshots
panel

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by ojwanganto** [comment]
Update the PR title to reflect the morgue module. Thanks

**Comment by its-kios09** [comment]
> Update the PR title to reflect the morgue module. Thanks

@ojwanganto  Thanks I will do so as I fix  the failed build

**Comment by donaldkibet** [comment]
ping @its-kios09 build error and conflicts need your attention. Thanks

**Comment by its-kios09** [comment]
> ping @its-kios09 build error and conflicts need your attention. Thanks

okay thanks @donaldkibet  let me address them

**Pull request merged**
