### PR TITLE
(feat) :Added empty state for "No search results" and "No provider avaailable" in Provider management ESM

### PR DESCRIPTION
**Pull request by its-kios09**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Screenshots

featSearch

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by ojwanganto** [comment]
Let's use standard styling for hover on tabs. We need a consistent UI across the system.
Also, consider:
1. Re-arranging the table columns to start with provider name or license
2. Drop serial no column. It is not useful in an EMR
3. The shouting alerts
4. If a tab is named 'missing property', we don't need to include the property in the table since the tab already signals it's missing

**Review by makombe — COMMENTED** [review]
Thanks @its-kios09. Please address the suggested changes then we can merge this in

**Comment by its-kios09** [comment]
provider

@ojwanganto @makombe I have updated the branch as per suggestions

**Comment by ojwanganto** [comment]
> provider
> 
> @ojwanganto @makombe I have updated the branch as per suggestions

Looks good. Thanks

**Pull request merged**
