### PR TITLE
Khp3 6618 align peer calendar with the UI design

### PR DESCRIPTION
**Pull request by Omoshlawi**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Screenshots

image

## Related Issue

https://thepalladiumgroup.atlassian.net/browse/KHP3-6618

## Other

*None.*

### CODE REVIEW

**Review by donaldkibet — APPROVED** [review]

**Comment by Omoshlawi** [comment]
@makombe thats not an issue, for a properly registered peer nd peer educator, it wont be disabled, everything will be well, it will work fine, its just that i was using super user who is not a patient nor properly registered peer educator.additionally when priviledges/roles apply well, peer calendar wont be available for none peer educators.

**Comment by makombe** [comment]
Does that mean you can still add peer/peer educator relationship to a non KVP @Omoshlawi ?

**Comment by Omoshlawi** [comment]
> Does that mean you can still add peer/peer educator relationship to a non KVP @Omoshlawi ?

No, you cant add a peer who is not enrolled to KVP Program.But that filtering is only done on the form where we add peer.
image

**Comment by Omoshlawi** [comment]
> > @makombe thats not an issue, for a properly registered peer nd peer educator, it wont be disabled, everything will be well, it will work fine, its just that i was using super user who is not a patient nor properly registered peer educator.additionally when priviledges/roles apply well, peer calendar wont be available for none peer educators.
> 
> Ok. But just ensure that the list only contains Peers/Peer educator. I expected if you loggedin with non KP provider super user should not be on the list. @Omoshlawi

A user who has no peer educator can not access the peer calendar dashboard, so when the configured roles pick up (It seems to to have picked up yet), the super user will not even see the peer calendar dashboard in the first place

**Pull request merged**
