### PR TITLE
Correctly display Blood pressure values

### PR DESCRIPTION
**Pull request by makombe**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## 
Screenshot from 2024-07-29 12-15-37
Screenshots

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Review by ojwanganto — DISMISSED** [review]
Thanks, @makombe

**Comment by donaldkibet** [comment]
cc @makombe seems we have an error with linting

**Comment by makombe** [comment]
> cc @makombe seems we have an error with linting

Let me look into it. Thanks

**Comment by ojwanganto** [comment]
ping @makombe

**Comment by makombe** [comment]
@donaldkibet @ojwanganto . This has been fixed. Thanks

**Comment by ojwanganto** [comment]
Thanks, @makombe. Over to you @donaldkibet

**Pull request merged**
