### PR TITLE
(feat) : mutate bills on successful mpesa payment

### PR DESCRIPTION
**Pull request by amosmachora**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
This PR adds the functionality to automatically add the paid mpesa amount to the bill tendered amount.

## Screenshots
https://github.com/user-attachments/assets/dcfd7c5e-7d94-4ce8-9ce1-b487c7d9bec5
## Related Issue

*None.*

## Other
cc @ojwanganto

### CODE REVIEW

**Comment by amosmachora** [comment]
image

@donaldkibet If you check out the above screenshot you will notice that the rendered payments tend to update even their date of payment. What I did was based majorly on your work on the payment form. If you do not mind could you help me figure out how to fix that bug? An Idea I had is instead of including the previous payments in the payload that is used to update the bill we only have the newly created payment. Would that work? What do you think?

See [here.](https://github.com/amosmachora/kenyaemr-esm-3.x/blob/5a7dcbc02476e2aa66a6871aa32b156729efd4db/packages/esm-billing-app/src/hooks/useRequestStatus.tsx#L18)

**Comment by ojwanganto** [comment]
@donaldkibet - did you figure this out? We really need this change in once all issues are addressed

**Comment by donaldkibet** [comment]
The bill endpoint to support the use case where we add only the current amount paid and retain payment history will require work on the backend to facilitate that.

**Comment by donaldkibet** [comment]
@ojwanganto @amosmachora the issue is because the endpoint for posting bill doesn't support use passing the `dateCreated` object. It seems it picks the date when the first payment was made. Will need to adjust this logic from the backend.

Screenshot 2024-09-04 at 17 32 42

See https://github.com/palladiumkenya/openmrs-module-kenyaEMRCashier/blob/a3c6ee19f59f6b1f966260aa436b99b68499fe55/omod/src/main/java/org/openmrs/module/kenyaemr/cashier/rest/resource/PaymentResource.java#L129

Am going to merge this in and @amosmachora can do a follow up if we need to include `dateCreated` on the payload or by default if not present take the current date time.

**Review by donaldkibet — APPROVED** [review]
Thanks @amosmachora

**Comment by amosmachora** [comment]
Thanks @donaldkibet I will be on the look out for when the backend is ready to support that functionalit and issue a PR on the same. Also if it is necessary for you guys to acquire mpesa credentials it is okay. Currently we are using credentials given to us by the support of @Injiri . Just be careful with the amount you are sending because it will deduct money from your mpesa account.

**Comment by ojwanganto** [comment]
> @amosmachora @ojwanganto should we have the operations team acquire MPESA credentials for us to use on test instance. The current deployed name is `INTECHX COMPUTER INNOVATION`

We have actually configured it with a real till number so be mindful of the amounts you charge. There will be NO REFUNDS hehe

**Pull request merged**
