### PR TITLE
(fix) : fix error on posting bill re-fund

### PR DESCRIPTION
**Pull request by donaldkibet**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

This PR fixes an issue with posting refunds for bill captured in error.

## Screenshots
https://github.com/user-attachments/assets/82df895b-9099-469b-857a-92ba41fd6e4c

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Review by makombe — APPROVED** [review]
Thanks @donaldkibet  LGTM
Also, seems the videos you normally provide can not be viewed on my end. Maybe you try another tool to create them. Thanks

**Review by its-kios09 — APPROVED** [review]
@donaldkibet  Thanks for me LGTM

**Comment by ojwanganto** [comment]
Thanks, @donaldkibet. I am also not able to play the attached video. I think we can merge this in to unblock any related testing.

**Comment by donaldkibet** [comment]
https://github.com/user-attachments/assets/f2262436-2175-4b47-b012-df73c61b0aa4

**Comment by donaldkibet** [comment]
Kapture 2024-08-19 at 14 59 06

**Comment by ojwanganto** [comment]
I can now see the video! Thanks :)

**Pull request merged**
