### PR TITLE
KHP3-6172 - (Refactor)  Billing/checkin form

### PR DESCRIPTION
**Pull request by its-kios09**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
summary:- https://thepalladiumgroup.atlassian.net/browse/KHP3-6172

## Screenshots
bilingcheckin

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by ojwanganto** [comment]
If one is exempted, they should not be billed.

**Comment by its-kios09** [comment]
> If one is exempted, they should not be billed.

Resolved

**Comment by its-kios09** [comment]
> Thanks @its-kios09. Please address suggested changes plus the comment by Antony.

Resolved

**Comment by ojwanganto** [comment]
The video is great. Thanks, @its-kios09. I have noted that for the exempted category, there is a big white space between billing information and the queue location. This, however, can be addressed in a follow-up PR it is a lot of work. Thanks

**Review by makombe — APPROVED** [review]
Thanks @its-kios09 LGTM

**Pull request merged**
