### PR TITLE
Khp3 6559 refactor lab manifest overview styling

### PR DESCRIPTION
**Pull request by Omoshlawi**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Screenshots
image

## Related Issue

https://thepalladiumgroup.atlassian.net/browse/KHP3-6559

## Other

*None.*

### CODE REVIEW

**Review by donaldkibet — CHANGES_REQUESTED** [review]
Thanks @Omoshlawi, i think for the summary cards, we might want to have a consistent design
e.g

Screenshot 2024-10-02 at 15 54 21

This is the home page metrics card. We should adopt similar styling. Its also important now to work with ted to have our work aligned. Thanks

**Comment by donaldkibet** [comment]
@ojwanganto, @makombe @its-kios09  whats are you thought on the colors that have been used here. IMO we should use whats recommended by the Carbon style guide to avoid having sections of our UI different from the rest.

**Review by donaldkibet — APPROVED** [review]

**Comment by ojwanganto** [comment]
> @ojwanganto, @makombe @its-kios09 whats are you thought on the colors that have been used here. IMO we should use whats recommended by the Carbon style guide to avoid having sections of our UI different from the rest.

Was there a resolution here? May be we needed one, however late

**Comment by Omoshlawi** [comment]
> Thanks @Omoshlawi, i think for the summary cards, we might want to have a consistent design e.g
> 
> Screenshot 2024-10-02 at 15 54 21
> 
> This is the home page metrics card. We should adopt similar styling. Its also important now to work with ted to have our work aligned. Thanks

@donaldkibet this was the design
image

**Pull request merged**
