### PR TITLE
(fix) : fix error on picking the correct bill total amount

### PR DESCRIPTION
**Pull request by munania**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary
Change total amount to reflect correctly in the invoice breakdown Change client balance/total amount due to show correct balance on posted bills

## Screenshots
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/35590825/9c85e711-f7cf-474d-99fd-0ca142231583

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by munania** [comment]
Uploading BILLING TOTALS.mp4…

**Comment by munania** [comment]
Uploading BILLING TOTALS.mp4…

**Comment by munania** [comment]
Uploading BILLING TOTALS.mp4…

**Comment by munania** [comment]
l

https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/35590825/9c85e711-f7cf-474d-99fd-0ca142231583

**Review by ojwanganto — APPROVED** [review]
Thanks, @munania

**Review by donaldkibet — APPROVED** [review]
LGTM Thanks @munania 🤝

**Pull request merged**
