### PR TITLE
Fix clockin to payment point bug

### PR DESCRIPTION
**Pull request by Omoshlawi**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Screenshots

https://github.com/user-attachments/assets/86873bc4-f1f7-428c-b2c5-b85ed9df6262

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by ojwanganto** [comment]
Thanks, @Omoshlawi

**Comment by amosmachora** [comment]
@Omoshlawi the cancel button was disabled by design. It meant that you just had to clock in at certain cash points to be able to do any billing functionality. I think enabling it defeats the whole purpose of the feature.

**Comment by Omoshlawi** [comment]
> @Omoshlawi the cancel button was disabled by design. It meant that you just had to clock in at certain cash points to be able to do any billing functionality. I think enabling it defeats the whole purpose of the feature.

Yeah @amosmachora , which worked fine with the previoud implementation.

Currently when you cancel you remain on the bill overview screen, meaning you go no where untill you clocki in.In short, you are only navigated to the claims screen or invoice screen when you clock in succesfully.

But from previous implementation, It first took you to the invoice screen then is shows the clocking modal after words which could be bypassed by esc key in keyboard, bt now we prevent the user from navigating to the screen in the first place before clockin in.

**Comment by donaldkibet** [comment]
@amosmachora  i do not have much context as you. Kindly give this a quick review. cc @Omoshlawi please fix the conflict

**Comment by ojwanganto** [comment]
@amosmachora - please review when you get a change

**Comment by amosmachora** [comment]
@donaldkibet I think you should add me to this repo as an outside collaborator for me to be able to do reviews. Also, @Omoshlawi on #465 I tried to fix this issue. Let's give it a chance and if the bug reoccurs we could try going your way. It's a tough nut to crack.

**Comment by donaldkibet** [comment]
@amosmachora added you as a maintainer in the repository.

**Comment by ojwanganto** [comment]
Can we please close on this and have it packaged?

**Comment by donaldkibet** [comment]
cc @amosmachora kindly address the conflict here

**Comment by ojwanganto** [comment]
@amosmachora please confirm that we don't need this change now

**Comment by amosmachora** [comment]
I suggest we close it for now. We can reopen it once the bug reoccurs.

**Pull request closed without merging**
