### PR TITLE
O3-3128: Add ability to show lab and drug order prices and stock levels

### PR DESCRIPTION
**Pull request by donaldkibet**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

see 👉🏽  https://openmrs.atlassian.net/browse/O3-3128

## Screenshots
https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/28008754/bfb391e7-920d-406b-9205-983b71a0a39a

## Related Issue
https://github.com/openmrs/openmrs-esm-patient-chart/pull/1818
## Other
@ojwanganto @patryllus  we will need to update the stock inventory endpoint to allow clinical staff access stock levels. 
*None.*

### CODE REVIEW

**Comment by ojwanganto** [comment]
Thanks, Don. This is awesome!

**Comment by ojwanganto** [comment]
Thanks, @gracepotma. It makes total sense. We'll need the help of the designers to get this done appropriately and I can reach out to our designers for better designs.

**Review by jecihjoy — COMMENTED** [review]
This is great @donaldkibet 
Just a little addition for services ie labs, procedures - the admin page allows configuring whether the service is available or not, this could be based on whether test reagents are available etc, on the ordering page apart from indicating the price, you could also indicate whether it's available or not, this would guide clinicians to ask patient to do the test outside and bring back results if lab test in unvailable

**Comment by donaldkibet** [comment]
> This is great @donaldkibet Just a little addition for services ie labs, procedures - the admin page allows configuring whether the service is available or not, this could be based on whether test reagents are available etc, on the ordering page apart from indicating the price, you could also indicate whether it's available or not, this would guide clinicians to ask patient to do the test outside and bring back results if lab test in unvailable

@jecihjoy am addressing this in a follow up PR.

**Pull request merged**
