### PR TITLE
WIP:Functionality to update billable services

### PR DESCRIPTION
**Pull request by agesa3**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [ ] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Screenshots

https://github.com/palladiumkenya/kenyaemr-esm-3.x/assets/47299413/1aa5c6b1-cc64-4394-bd73-989ab87cec55

*None.*

## Related Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by ojwanganto** [comment]
Nice

**Comment by donaldkibet** [comment]
Thanks @agesa3 looking great 🚀 , could we leverage the workspace to show the form since thats the standard O3 uses for data capture.

**Comment by agesa3** [comment]
> Thanks @agesa3 looking great 🚀 , could we leverage the workspace to show the form since thats the standard O3 uses for data capture.

This is noted @donaldkibet let me refactor

**Comment by ojwanganto** [comment]
@agesa3 can we have this done by today?

**Comment by agesa3** [comment]
> @agesa3 can we have this done by today?

Hopefully  will be done by close of day am currently working on it

**Pull request closed without merging**
